### ISSUE TITLE
Doesn't work for multiline generic types

### ISSUE THREAD

**Issue by LorenzHenk** [thebearingedge/vscode-sql-lit#13]
Hey, I've found a small issue when highlighting sql with multiline generic types:

![image](https://user-images.githubusercontent.com/10603631/223170771-93abc7a9-49f6-49e7-b865-90ebdb23475d.png)

as you can see, in `testFailing` the query is not highlighted (colored as string). This is because the [`begin` span](https://github.com/thebearingedge/vscode-sql-lit/blob/master/syntaxes/sql-lit.json#L16) spans multiple lines.

code:
```ts
export function testWorking() {
  return sql<{ value: number }>`SELECT 1 AS "value"`;
}

export function testFailing() {
  return sql<{ value: number }
  >`SELECT 1 AS "value"`;
}
```

**Comment by thebearingedge** [comment]
@LorenzHenk thanks, I'm looking into it and initially, it's looking pretty tough.

The [language grammar docs](https://macromates.com/manual/en/language_grammars#language_rules) seem to suggest that there are limitations on how patterns are matched across lines.

As a sanity check, I've also looked for similar breakage in the [styled-components](https://github.com/styled-components/vscode-styled-components) syntax highlighting, which is supposed to switch to CSS highlighting within a tagged template literal.

![code](https://user-images.githubusercontent.com/7432943/223195394-838fb903-1df4-4463-a053-ccb6cf25c215.png)

I'll mess with it a bit as time allows though, in case there is a reasonably straightforward fix.

**Comment by thebearingedge** [comment]
monokai dark soda seems to break horribly, but there are subtle inconsistencies with other themes as well, including the default light / dark themes

![code](https://user-images.githubusercontent.com/7432943/223198249-da6ef9f2-a311-4d7f-ae78-9d36f33bf1f9.png)
![Untitled](https://user-images.githubusercontent.com/7432943/223198767-b28d9f84-f743-4c23-abd7-224456c2a725.png)
![Untitled](https://user-images.githubusercontent.com/7432943/223198991-e07f4f70-ea79-4ebd-a463-f5ebc1b86351.png)

**Comment by thebearingedge** [comment]
It looks like this is a problem that grammar authors have run into.

https://github.com/microsoft/vscode-textmate/issues/41

As far as I can tell, it's just a limitation of how tmLanguage matching works (line-by-line). Since our `"begin"` is written to match from the `sql` tag all the way through to the <code>`</code> template start, any new line in between will invalidate the match.

Closing for now, but if someone has another idea / approach, it's certainly welcome!

**Comment by net** [comment]
I believe a workaround is to use the comment prefix and tagged literal together:

```js
sql<{
  value: number
}[]>/* sql */ `
  SELECT 1 value;
`
```

It's not ideal, but perhaps this workaround should be documented.

**Comment by karlhorky** [comment]
VS Code itself somehow gets around the limitations and can do correct syntax highlighting over multiple lines, maybe with [Semantic Highlighting](https://github.com/microsoft/vscode-textmate/issues/41#issuecomment-780945468) by @aeschli and @alexdima.

I also see some changes with regular expressions, which @sheetalkamat has also been maintaining:

- https://github.com/microsoft/TypeScript-TmLanguage/commit/88a7e09e927ea2a135db60810d6a1fe8f589d165

So maybe there is a way for a VS Code extension to also achieve this, by also using this Semantic Highlighting / these regular expressions.

The TextMate grammar limitations have also been explored in the following [SQL tagged template literals](https://marketplace.visualstudio.com/items?itemName=frigus02.vscode-sql-tagged-template-literals-syntax-only) VS Code extension, but no solution has yet appeared:

- https://github.com/frigus02/vscode-sql-tagged-template-literals/issues/20
- https://github.com/frigus02/vscode-sql-tagged-template-literals/pull/21

**Comment by karlhorky** [comment]
## Workaround (`/* sql */` comment)

Add a `/* sql */` comment after the multi-line generic

```diff
sql<{
  value: number
-}[]>`
+}[]>/* sql */ `
  SELECT 1 value;
`
```

Credit: @Net in https://github.com/thebearingedge/vscode-sql-lit/issues/13#issuecomment-1550486134
