### ISSUE TITLE
Breaks on *.sql``

### ISSUE THREAD

**Issue by net** [thebearingedge/vscode-sql-lit#14]
We connect to multiple databases, and so sometimes import multiple database objects under different names:

```js
import db from 'src/db'
import herokuDB from 'src/herokuDB'

await db.sql`SELECT 1`
await herokuDB.sql`SELECT 1`

...
```

This extension works fine with `db.sql`, but with any other module name, such as `herokuDB.sql`, JS syntax highlighting breaks after end of the template literal.

**Comment by thebearingedge** [comment]
Hi @net thanks for opening the issue! I think a `.sql` tag method should be supported 👍. I'm def open to a PR if this is needed right away, but I'll leave the issue open for when I have time.

**Comment by thebearingedge** [comment]
@net v 0.7 is live!
https://marketplace.visualstudio.com/items?itemName=thebearingedge.vscode-sql-lit

**Comment by net** [comment]
@thebearingedge amazing, thanks!
