### ISSUE TITLE
Thanks so much for this!

### ISSUE THREAD

**Issue by karlhorky** [thebearingedge/vscode-sql-lit#2]
Just wanted to come and say thanks for this extension, very cool!

I was using https://github.com/ForbesLindesay/vscode-sql-template-literal up until now, but because of https://github.com/ForbesLindesay/vscode-sql-template-literal/issues/13, moving over here now!

Closing :)

**Comment by thebearingedge** [comment]
Hey @karlhorky  thanks for the positive feedback and the review!

Best regards!
