### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by LorenzHenk** [thebearingedge/vscode-sql-lit#6]
Hey, this extension looks very interesting!

Would you be open to publishing this extension on Open VSX , so that it can be used e.g. via gitpod?

More information: https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions#where-do-i-find-extensions

**Comment by thebearingedge** [comment]
Hi @LorenzHenk thanks for the tip

I will take a look!

**Comment by thebearingedge** [comment]
Hi @LorenzHenk, I finally got around to doing this. The extension is published and I have a pending namespace claim with open-vsx.

https://open-vsx.org/extension/thebearingedge/vscode-sql-lit
https://github.com/EclipseFdn/open-vsx.org/issues/1597

Cheers!

**Comment by LorenzHenk** [comment]
Awesome, thanks a lot!
