### ISSUE TITLE
Explain the usage of `sql`

### ISSUE THREAD

**Issue by shadoath** [thebearingedge/vscode-sql-lit#7]
How do I import the `sql` command is it from another package or what. I'm a bit lost on how to use it and how it can return back the typed value.

**Comment by shadoath** [comment]
Example: 
```
const query = sql<
    FundingSourceRegistration_db[]
  >`INSERT INTO funding_source_registrations(
	student_id,
	funding_source_id,
	funding_source_student_id,
	funding_source_student_number
  )
  VALUES (
	${student_id},
	${funding_source_id},
	${funding_source_student_id},
	${funding_source_student_number}
  )
  RETURNING *;`

  try {
    return await db.query(query)
  } catch (e) {
    console.error(e)
    return []
  }
```

This has an error with the usage of `sql...` => "Cannot find name 'sql'.ts(2304)" 

My assumption is that I need to use `const sql = require("sql-template-strings")` Is that correct?

**Comment by thebearingedge** [comment]
Hi @shadoath, yes in the examples `sql` is referring to some other package 👍. You should be able to use one of these.

- [`postgres`](https://www.npmjs.com/package/postgres)
- [`slonik`](https://www.npmjs.com/package/slonik)
- [`@slonik/typegen`](https://www.npmjs.com/package/@slonik/typegen)
- [`sql-template-strings`](https://www.npmjs.com/package/sql-template-strings)
